"""Export the live dashboard as a static HTML + JSON pair to ./public/.

Reads the same data the live dashboard exposes via /api/state and
/api/appraisals, freezes it as JSON snapshots, and writes a static
index.html that the dashboard's frontend can boot from. Suitable for
Netlify / GitHub Pages / any static host.

Usage:
    python export_static.py [--out PATH]

Default output: ./public/

Run this from the appraiser cron at the end of each cycle (or manually
to refresh the public snapshot). The static site is read-only — no
live polling — but auto-refreshes when the user reloads.
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

# Reuse the live dashboard's query functions and HTML template.
sys.path.insert(0, str(Path(__file__).parent))
import dashboard  # noqa: E402


STATIC_BANNER = """
<!-- Static snapshot — generated by export_static.py. Reloads from
     ./api/state.json and ./api/appraisals.json instead of live HTTP. -->
"""

# A tiny shim: replace the live fetch URLs with the static JSON files.
LIVE_TO_STATIC = [
    ("/api/state", "./api/state.json"),
    ("/api/appraisals", "./api/appraisals.json"),
]


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--out", default="public",
                   help="Output directory (default: public/)")
    args = p.parse_args()

    out = Path(args.out).resolve()
    api_dir = out / "api"
    api_dir.mkdir(parents=True, exist_ok=True)

    # 1. Snapshot the two JSON endpoints.
    state_payload = dashboard.query_state()
    appr_payload = dashboard.query_appraisals()
    (api_dir / "state.json").write_text(
        json.dumps(state_payload, indent=2, default=str), encoding="utf-8")
    (api_dir / "appraisals.json").write_text(
        json.dumps(appr_payload, indent=2, default=str), encoding="utf-8")

    # 2. Take the live HTML, swap fetch URLs, mark as static.
    html = dashboard.INDEX_HTML
    for live, static in LIVE_TO_STATIC:
        html = html.replace(f"fetch('{live}')", f"fetch('{static}')")
        html = html.replace(f"fetch(\"{live}\")", f"fetch(\"{static}\")")
    html = html.replace("<head>", "<head>" + STATIC_BANNER, 1)
    # Strip the auto-refresh interval — static snapshots don't change
    # until the next export, so polling every 3 s is wasted CPU.
    html = html.replace("setInterval(refresh, 3000);",
                        "/* static snapshot — refresh disabled */")
    html = html.replace("setInterval(refreshAppr, 5000);",
                        "/* static snapshot — refresh disabled */")
    (out / "index.html").write_text(html, encoding="utf-8")

    # 3. A minimal Netlify config — drop any redirects / headers later.
    netlify_toml = out / "_netlify.toml.example"
    netlify_toml.write_text(
        "[build]\n"
        "  publish = \"public\"\n"
        "  # If you push the whole repo, point Netlify to the public/ dir\n"
        "  # generated by export_static.py.\n",
        encoding="utf-8")

    print(json.dumps({
        "out": str(out),
        "files": ["index.html", "api/state.json", "api/appraisals.json",
                  "_netlify.toml.example"],
        "appraised_total": appr_payload.get("total"),
        "indexed_total": state_payload.get("total"),
    }, indent=2))


if __name__ == "__main__":
    main()
